name: kampushare
description: "KampuShare App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  firebase_core: ^4.1.1
  firebase_auth: 6.0.1
  cloud_firestore: 6.0.1
  firebase_storage: 13.0.1
  image_picker: 1.1.2
  provider: 6.1.5
  uuid: 4.5.1
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
    - assets/users_products.json
    
  uses-material-design: true

flutter_launcher_icons:
  color: "white"
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  
